--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ShockedPlot7560/FactionMaster
build-by-default: true
branches:
- stable
- dev
- pmmp4
- next-minor
projects:
  FactionMaster:
    path: ""
    icon: "icon.png"
    libs:
    - src: Vecnavium/FormsUI/FormsUI
      version: ^1.1.1
    - src: CortexPE/Commando/Commando
      version: ^3.0.0
      branch: PM4
    - src: ifera-mc/UpdateNotifier/UpdateNotifier
      version: ^2.1.0
      branch: API-4.0.0
    - src: ifera-mc/ConfigUpdater/ConfigUpdater
      version: ^1.2.0
      branch: PM4
    - src: muqsit/simplepackethandler/SimplePacketHandler
      version: ^0.0.1
    lint: false
...
