name: FactionMaster
author: ShockedPlot7560
version: 3.1.4
api: 3.0.0
main: ShockedPlot7560\FactionMaster\Main
description: "Full configurable and modulable faction plugin with a lot of configuration"
softdepend: ["ScoreHud"]
virions: ["Commando", "libFormAPI"]

permissions:
  factionmaster.scoreboard.place:
    description: "Allow the player to place scoreboard"
    default: "op"
  factionmaster.synchro.launch:
    description: "Allow the player to launch database synchronisation"
    default: "op"
  factionmaster.flag.add:
    description: "Allow the player to add area to flag"
    default: "op"
  factionmaster.flag.remove:
    description: "Allow the player to remove flag of area"
    default: "op"
  factionmaster.extension.list:
    description: "Allow the player to remove flag of area"
    default: "op"
