name: FactionMaster
author: ShockedPlot7560
version: 4.0.0
api: 4.0.0
main: ShockedPlot7560\FactionMaster\Main
src-namespace-prefix: ShockedPlot7560\FactionMaster
description: "Full configurable and modulable faction plugin with resource pack"
softdepend: ["ScoreHud"]
virions: ["Commando", "libFormAPI", "PacketHandler", "UpdateNotifier", "ConfigUpdater"]

permissions:
  factionmaster.leaderboard.place:
    description: "Allow the player to place leaderboard"
    default: "op"
  factionmaster.leaderboard.remove:
    description: "Allow the player to remove leaderboard"
    default: "op"
  factionmaster.synchro.launch:
    description: "Allow the player to launch database synchronisation"
    default: "op"
  factionmaster.flag.add:
    description: "Allow the player to add area to flag"
    default: "op"
  factionmaster.flag.remove:
    description: "Allow the player to remove flag of area"
    default: "op"
  factionmaster.extension.list:
    description: "Allow the player to remove flag of area"
    default: "op"
