<?php

namespace ShockedPlot7560\FactionMaster\Utils;

interface Ids {

    const RECRUIT_ID = 0;
    const MEMBER_ID = 1;
    const COOWNER_ID = 2;
    const OWNER_ID = 3;

    const PUBLIC_VISIBILITY = 0;
    const PRIVATE_VISIBILITY = 1;
    const INVITATION_VISIBILITY = 2;

    const PERMISSION_CHANGE_MEMBER_RANK = 0;
    const PERMISSION_KICK_MEMBER = 1;
    const PERMISSION_ACCEPT_MEMBER_DEMAND = 2;
    const PERMISSION_REFUSE_MEMBER_DEMAND = 3;
    const PERMISSION_SEND_MEMBER_INVITATION = 4;
    const PERMISSION_DELETE_PENDING_MEMBER_INVITATION = 5;
    const PERMISSION_ACCEPT_ALLIANCE_DEMAND = 6;
    const PERMISSION_REFUSE_ALLIANCE_DEMAND = 7;
    const PERMISSION_SEND_ALLIANCE_INVITATION = 8;
    const PERMISSION_DELETE_PENDING_ALLIANCE_INVITATION = 9;
    const PERMISSION_MANAGE_LOWER_RANK_PERMISSIONS = 10;
    const PERMISSION_CHANGE_FACTION_MESSAGE = 11;
    const PERMISSION_CHANGE_FACTION_DESCRIPTION = 12;
    const PERMISSION_DELETE_FACTION_HOME = 13;
    const PERMISSION_ADD_FACTION_HOME = 14;
    const PERMISSION_TP_FACTION_HOME = 15;
    const PERMISSION_CHANGE_FACTION_VISIBILITY = 16;
    const PERMISSION_BREAK_ALLIANCE = 17;

}